FROM apache/airflow:2.7.3-python3.10 

# Установите необходимые системные зависимости
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Копируем файл с зависимостями
COPY requirements.txt ./tmp/requirements.txt

# Обновляем pip до последней версии
RUN pip install -U pip

# Устанавливаем зависимости из requirements.txt
RUN pip install -r ./tmp/requirements.txt
